import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Weato Title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>홈페이지</h1>

        <ul className="list-disc list-inside">
          <li>
            홈페이지 : <a href="/">weato.net</a>
          </li>

          <br />

          <li>
            마이페이지 - 프로필 탭 :
            <a href="/mypage?tab=profile">weato.net/mypage?tab=profile</a>
          </li>
          <li>
            마이페이지 - 북마크 탭 :
            <a href="/mypage/?tab=bookmarks">weato.net/mypage?tab=bookmarks</a>
          </li>
          <li>
            마이페이지 - 커뮤니티 탭 :
            <a href="/mypage/?tab=community">weato.net/mypage?tab=community</a>
          </li>
          <li>
            마이페이지 - 회원 정보 변경 :
            <a href="/mypage/edit">weato.net/mypage/edit</a>
          </li>

          <br />

          <li>
            네이버 로그인 표시 화면 : <a href="/login">weato.net/login</a>
          </li>
          <li>
            첫 회원가입 시 : <a href="/signup">weato.net/signup</a>
          </li>
          <li>
            회원가입 성공 :
            <a href="/signup/success">weato.net/signup/success</a>
          </li>
          <li>
            추가 회원 정보 입력 :
            <a href="/signup/more">weato.net/signup/more</a>
          </li>

          <br />

          <li>
            뉴스레터 홈 : <a href="/login">weato.net/newsletter</a>
          </li>
          <li>
            뉴스레터 - 상세 페이지 :
            <a href="/login">weato.net/newsletter/뉴스레터_번호</a>
          </li>

          <br />

          <li>
            커뮤니티 홈 : <a href="/community">weato.net/community</a>
          </li>
          <li>
            커뮤니티 - 핫토픽 :
            <a href="/community?tab=hot">weato.net/community?tab=hot</a>
          </li>
          <li>
            커뮤니티 - 나만의 관리법 :
            <a href="/community?tab=knowhow">weato.net/community?tab=knowhow</a>
          </li>
          <li>
            커뮤니티 - 질문 :
            <a href="/community?tab=questions">
              weato.net/community?tab=questions
            </a>
          </li>
          <li>
            커뮤니티 - 상세 페이지 :
            <a href="/community/post/포스트_번호">
              weato.net/community/post/포스트_번호
            </a>
          </li>
          <li>
            커뮤니티 - 새로운 글 작성 :
            <a href="/community/post/new">weato.net/community/post/new</a>
          </li>

          <br />

          <li>
            검색창 : <a href="/search">weato.net/search</a>
          </li>
          <li>
            검색 결과 :
            <a href="/search/result">weato.net/search/result?keyword=검색어</a>
          </li>
          <li>
            검색 결과 - 뉴스레터 필터링 :
            <a href="/search/result/newsletter">
              weato.net/search/result/newsletter?keyword=검색어
            </a>
          </li>
          <li>
            검색 결과 - 커뮤니티 글 필터링 :
            <a href="/search/result/community">
              weato.net/search/result/community?keyword=검색어
            </a>
          </li>
        </ul>
      </main>

      <footer>Footer</footer>
    </div>
  );
}
